//Import
const { createUser, createProduct } = require("./db");

const fakeInfo = async () => {
  try {
    const users = await Promise.all([
      createUser({
        first_name: "Lilly",
        last_name: "Williamson",
        email: "lilly_williamson@gmail.com",
        password: "lillywil1",
        address: "28 Cobblestone Circle, Milledgeville, GA 31061",
        payment_info: "Debit Card",
      }),
      createUser({
        first_name: "Emerson",
        last_name: "Foley",
        email: "emerson_foley@gmail.com",
        password: "emerfol2",
        address: "55 Oak Circle, Chippewa Falls, WI 54729",
        payment_info: "Credit Card",
      }),
      createUser({
        first_name: "Alana",
        last_name: "Bell",
        email: "alana_bell@gmail.com",
        password: "alanbel3",
        address: "7239 Pleasant Road, Dracut, MA 01826",
        payment_info: "Debit Card",
      }),
      createUser({
        first_name: "Thalia",
        last_name: "Stark",
        email: "thalia_stark@gmail.com",
        password: "thaista4",
        address: "770 Garfield Lane, Danbury, CT 06810",
        payment_info: "Credit Card",
      }),
      createUser({
        first_name: "Dion",
        last_name: "Page",
        email: "dion_page@gmail.com",
        password: "dionpag5",
        address: "37 East Ave., Sarasota, FL 34231",
        payment_info: "Credit Card",
      }),
    ]);

    const products = await Promise.all([
      //Clothing & Shoes
      createProduct({
        name:"Nike Air Force 1 Shadow",
        description:"Everything you love about the AF1—but doubled! Layered materials like linen-evoking textiles and synthetic leather pair with an exaggerated midsole and a pop of pastels to bring you double the style.",
        department:"Clothing & Shoes",
        price:"",
        status:"Best Sellers",
        imageUrl:"https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=2187&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Clothing & Shoes",
        price:"",
        status:"Deals",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Clothing & Shoes",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Clothing & Shoes",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Clothing & Shoes",
        price:"",
        status:"",
        imageUrl:"",
      }),
      //Electronics
      createProduct({
        name:"",
        description:"",
        department:"Electronics",
        price:"",
        status:"Best Sellers",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Electronics",
        price:"",
        status:"Deals",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Electronics",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Electronics",
        price:"",
        status:"",
        imageUrl:"",
      }),
      //Home
      createProduct({
        name:"",
        description:"",
        department:"Home",
        price:"",
        status:"Best Sellers",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Home",
        price:"",
        status:"Deals",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Home",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Home",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Home",
        price:"",
        status:"",
        imageUrl:"",
      }),
      //Office Products
      createProduct({
        name:"",
        description:"",
        department:"Office Products",
        price:"",
        status:"Best Sellers",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Office Products",
        price:"",
        status:"Deals",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Office Products",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Office Products",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Office Products",
        price:"",
        status:"",
        imageUrl:"",
      }),
      //Toys & Games
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"Best Sellers",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"Deals",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      //Garden & Outdoors
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Toys & Games",
        price:"",
        status:"",
        imageUrl:"",
      }),
      //Health & Beauty
      createProduct({
        name:"",
        description:"",
        department:"Health & Beauty",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Health & Beauty",
        price:"",
        status:"Deals",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Health & Beauty",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Health & Beauty",
        price:"",
        status:"",
        imageUrl:"",
      }),
      createProduct({
        name:"",
        description:"",
        department:"Health & Beauty",
        price:"",
        status:"",
        imageUrl:"",
      }),
    ]);

    return { users, products };
  } catch (err) {
    console.error("failed loading", err);
  }
};

//export
module.exports = { fakeInfo };
